### PR TITLE
Doc docker devenv

### PR DESCRIPTION
**Pull request by sbellem**

### CODE REVIEW

**Comment by ttmc** [comment]
On line 18 of `CONTRIBUTING.rst`, which is currently:
```text
Report bugs at https://github.com/bigchaindb/bigchaindb_driver/issues.
```

I think `bigchaindb_driver` should be `bigchaindb-driver`. I tried the link as-is and ended up on GitHub's 404 page.

**Comment by ttmc** [comment]
There are more instances of `bigchaindb_driver` (rather than `bigchaindb-driver`) throughout `CONTRIBUTING.rst`; maybe do a search and replace?

**Comment by sbellem** [comment]
Thanks @ttmc, just pushed the fixes

**Comment by ttmc** [comment]
The numbering in the **Get Started!** subsection of `CONTRIBUTING.rst` is off. It goes, 1. 2. 3. 5. 6. 7 8.. 7. (The number of periods after each number also varies.)

**Comment by sbellem** [comment]
@ttmc thanks again!

**Comment by ttmc** [comment]
Also in the **Get Started!** subsection of `CONTRIBUTING.rst`, it says to do:
```text
$ docker-compose up -d rethinkdb
```
but that results in:
```text
Creating network "bigchaindbdriver_default" with the default driver
ERROR: No such service: rethinkdb
```
Looking inside the `docker-compose.yml` file, it seems maybe you meant to suggest doing:
```text
docker-compose up -d rdb
```

**Comment by sbellem** [comment]
@ttmc yes, it was `rethinkdb` initially, and was renamed to `rdb` for brevity's sake

**Comment by ttmc** [comment]
:+1:

**Pull request merged**
